### ISSUE TITLE
Crash on API 26 

### ISSUE THREAD

**Issue by kgundula** [KudzieChase/ChaseMusicX#1]
App crashes on app start : Probably to do with permissions not being authorized.

Device : Nexus Emulator API 26 
Device : Pixel 3a Emulator API 28

`2020-01-24 11:14:31.359 13206-13234/com.chase.kudzie.chasemusic E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.chase.kudzie.chasemusic, PID: 13206
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=13206, uid=10087 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1943)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:754)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at com.chase.kudzie.chasemusic.data.loaders.SongLoader.getAll(SongLoader.kt:40)
        at com.chase.kudzie.chasemusic.data.repository.SongRepositoryImpl.getSongs(SongRepositoryImpl.kt:21)
        at com.chase.kudzie.chasemusic.domain.interactor.browse.song.GetSongs.invoke(GetSongs.kt:12)
        at com.chase.kudzie.chasemusic.viewmodel.SongViewModel$1$1.invokeSuspend(SongViewModel.kt:24)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

**Comment by KudzieChase** [comment]
Thank you for that. Yes it is a runtime permission issue. I will fix it in a bit.
